FROM node:20-alpine
WORKDIR '/app'
COPY ./package.json .
# prevent postinstall scripts from running on install
RUN npm config set ignore-scripts true
RUN npm install
# manually install esbuild
RUN npm install esbuild --no-save --ignore-scripts
# enable postinstall scripts back
RUN npm config set ignore-scripts false
COPY . .
CMD ["npm","run","dev"]
