# to run for local development
version: '2'
services:
  web:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
      - POCKETBASE_URL=http://pocketbase:8090
    ports:
      - '8080:5173'
    depends_on:
      pocketbase:
        condition: service_healthy
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_data:/pb_data
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5  
