version: '2'
  # for running on linode server to build production app
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
  web:
    build: 
      context: ./client
    container_name: frontend
    environment:
      - WDS_SOCKET_PORT=0
      - VITE_POCKETBASE_URL=http://pocketbase:8090
    networks:
      - app-network
  trade:
    build: 
      context: ./trading-service
    container_name: trade
    environment:
      - POCKETBASE_URL=${POCKETBASE_URL}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - app-network
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_data:/pb_data
    networks:
      - app-network
networks:
  app-network:
