# to run locally with production containers 
version: '2'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
  web:
    build: 
      context: ./client
    container_name: frontend
    environment:
      - WDS_SOCKET_PORT=0
      - VITE_POCKETBASE_URL=http://pocketbase:8090
  trade:
    build: 
      context: ./trading-service
    container_name: trade
    env_file:
      - ./server/.env.production
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./pocketbase/pb_data:/pb_data
  tests:
    build: 
      context: ./trading-service
      dockerfile: Dockerfile.dev
    command: ["npm","run","test"]
