upstream web {
  server web:80;
}

upstream pocketbase {
  server pocketbase:8090;
}

server {
  listen 80;
  server_name dcabot.ai;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name dcabot.ai;

  ssl_certificate /etc/letsencrypt/live/dcabot.ai/fullchain.pem 
  ssl_certificate_key /etc/letsencrypt/live/dcabot.ai/privkey.pem

  location / {
    proxy_pass http://web;
  }

  location /ws {
    proxy_pass http://web;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }

  location /api {
    # rewrite /api/(.*) $1 break;
    proxy_pass http://pocketbase;
  }

}


