FROM nginx

# Update the package repositories
RUN apt-get update

# Install wget
RUN apt-get install -y wget

COPY ./default.conf.dev /etc/nginx/conf.d/default.conf

# Install Dockerize
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# Update the entrypoint to use Dockerize
ENTRYPOINT ["dockerize", "-wait", "tcp://web:5173;", "-timeout", "1m", "nginx", "-g", "'daemon off;'"]
